### PR TITLE
WIP deal with ETree being deprecated in python 3.9

### PR DESCRIPTION
**Pull request by colinxfleming**

### CODE REVIEW

**Comment by colinxfleming** [comment]
sorry team bandwidth, didn't mean for you all to be automagically tagged in while I was making this compat with newer versions of python

**Comment by ajrice6713** [comment]
Hey @colinxfleming - no worries! Thanks for opening this PR and feel free to let us know if you need anything, or when it's ready for review.

**Review by bpateldx — CHANGES_REQUESTED** [review]
The only unit test is commented out. How confident are we that this change has not broken anything? Advise to add Unit Tests for each function being touched - `_from_xml` and `_post_data`

**Comment by hamermike** [comment]
Closing without recent activity. Feel free to open again if that changes!

**Pull request closed without merging**
